title: MidnightOS docs
description: Docs for MidnightOS
theme: just-the-docs

color_scheme: dark

url: https://midnightos.github.io/docs/

callouts:
  warning:
    title: Warning
    color: red

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
